image: mvn-pb162:v1.0

coverage:
   script:
    - mvn clean install -Dmaven.test.failure.ignore=true
    - "cat target/site/jacoco-ut/index.html"
   tags:
    - shared-fi
build:
  script:
    - mvn clean install -Dmaven.test.failure.ignore=true
      # - mvn clean install -B  -Dcheckstyle.fail=false
  tags:
    - shared-fi
