image: maven:3.5.0-jdk-8

before_script:
    - apt-get update
    - apt-get -y install openjfx
build:
  script:
    - mvn clean install -B  -Dcheckstyle.fail=false
    - "cat target/site/jacoco-ut/index.html"
  tags:
    - shared-fi
